// Generates fonts.css: the @font-face rules with the woff2 files inlined as
// data URLs, because `bb plugin build` has no loader for font files.
// Regenerate after changing a font: npm run fonts
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

interface Face {
  family: string;
  file: string;
  weight: string;
  format: "woff2" | "woff2-variations";
}

const FACES: readonly Face[] = [
  { family: "Tutor Archivo", file: "archivo-variable.woff2", weight: "300 800", format: "woff2-variations" },
  { family: "Tutor JetBrains Mono", file: "jetbrains-mono-variable.woff2", weight: "100 800", format: "woff2-variations" },
  { family: "Tutor Spectral", file: "spectral-400.woff2", weight: "400", format: "woff2" },
  { family: "Tutor Spectral", file: "spectral-500.woff2", weight: "500", format: "woff2" },
  { family: "Tutor Spectral", file: "spectral-600.woff2", weight: "600", format: "woff2" },
];

const DIR = fileURLToPath(new URL(".", import.meta.url));
export const FONTS_CSS = `${DIR}fonts.css`;

export function renderFontsCss(): string {
  const header = "/* Generated by app/fonts/embed.ts from the .woff2 files beside it. Do not edit. */\n";
  return (
    header +
    FACES.map((face) => {
      const data = readFileSync(`${DIR}${face.file}`).toString("base64");
      return [
        "@font-face {",
        `  font-family: "${face.family}";`,
        `  src: url("data:font/woff2;base64,${data}") format("${face.format}");`,
        `  font-weight: ${face.weight};`,
        "  font-style: normal;",
        "  font-display: swap;",
        "}",
      ].join("\n");
    }).join("\n") +
    "\n"
  );
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(FONTS_CSS, renderFontsCss());
}
