// Generates themes/paper.css, the BB theme the manifest contributes
// (`bb.themes`, id "paper"): the Archivo @font-face inlined as a data URL,
// then paper.palette.css. A theme is one CSS file that BB injects app-wide,
// so the font cannot be a separate file. Regenerate: npm run fonts
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { renderFontFaces } from "../fonts/embed.ts";

export const PALETTE_CSS = fileURLToPath(new URL("./paper.palette.css", import.meta.url));
export const THEME_CSS = fileURLToPath(new URL("../../themes/paper.css", import.meta.url));

export function renderThemeCss(): string {
  return [
    "/* Generated by app/theme/build.ts from app/theme/paper.palette.css and app/fonts. Do not edit. */",
    renderFontFaces("Tutor Archivo"),
    "",
    readFileSync(PALETTE_CSS, "utf8"),
  ].join("\n");
}

/** The `--token: value` declarations of the block that starts with `selector {`. */
export function paletteBlock(css: string, selector: string): Record<string, string> {
  const start = css.indexOf(`${selector} {`);
  if (start === -1) throw new Error(`no ${JSON.stringify(selector)} block`);
  const end = css.indexOf("}", start);
  const tokens: Record<string, string> = {};
  for (const match of css.slice(start, end).matchAll(/(--[\w-]+):\s*([^;]+);/g)) {
    const [, name, value] = match;
    if (name !== undefined && value !== undefined) tokens[name] = value.trim();
  }
  return tokens;
}

function luminance(hex: string): number {
  const match = /^#([0-9a-f]{6})$/i.exec(hex);
  if (match?.[1] === undefined) throw new Error(`not a #rrggbb colour: ${hex}`);
  const value = Number.parseInt(match[1], 16);
  const [r, g, b] = [value >> 16, (value >> 8) & 0xff, value & 0xff].map((channel) => {
    const c = channel / 255;
    return c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4;
  }) as [number, number, number];
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}

/** WCAG 2 contrast ratio of two #rrggbb colours. */
export function contrast(a: string, b: string): number {
  const [light, dark] = [luminance(a), luminance(b)].sort((x, y) => y - x) as [number, number];
  return (light + 0.05) / (dark + 0.05);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(THEME_CSS, renderThemeCss());
}
