#!/usr/bin/env bash
# Bring up (or re-attach to) the tutor-dev harness container: a devcontainer
# built from this repo's local src/bb Feature (standalone, autoStart), with the
# containerised BB published on host loopback at http://127.0.0.1:$TUTOR_DEV_PORT.
#
# Idempotent: re-running reuses a running container, starts a stopped one, and
# recreates it only when the generated config or the src/bb Feature changed.
#   --rebuild    force-recreate the container (keeps BB state)
#   --no-cache   with a (re)create, build the image with --no-cache
set -euo pipefail
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

rebuild=false no_cache=false
for arg in "$@"; do
    case "$arg" in
        --rebuild) rebuild=true ;;
        --no-cache) no_cache=true ;;
        -h|--help) sed -n '2,10p' "$0"; exit 0 ;;
        *) td_die "unknown argument: $arg" ;;
    esac
done

td_guard_ports
docker info >/dev/null 2>&1 || td_die "cannot talk to docker (in a sandbox? run with docker socket access)"
[ -x "$DEVCONTAINER" ] || command -v "$DEVCONTAINER" >/dev/null 2>&1 || td_die "devcontainer CLI not found (set DEVCONTAINER=...)"
[ -d "$TUTOR_DEV_MOUNT" ] || td_die "TUTOR_DEV_MOUNT $TUTOR_DEV_MOUNT does not exist"
case "$TUTOR_DEV_STATE/" in "$TUTOR_DEV_MOUNT"/*) ;; *) td_die "TUTOR_DEV_HOME must be inside TUTOR_DEV_MOUNT so BB state persists on the host" ;; esac

# 1. Generate the devcontainer workspace. Dev Containers only accepts local
#    Features beneath the consuming .devcontainer directory (see
#    examples/bb-standalone), so copy src/bb there fresh on every run.
dc_dir="$TUTOR_DEV_WORKSPACE/.devcontainer"
mkdir -p "$dc_dir/features" "$TUTOR_DEV_STATE"
chmod 0700 "$TUTOR_DEV_STATE"
rm -rf "$dc_dir/features/bb"
cp -a "$TUTOR_DEV_REPO/src/bb" "$dc_dir/features/bb"

TD_NAME="$TUTOR_DEV_NAME" TD_PORT="$TUTOR_DEV_PORT" TD_RELAY="$TUTOR_DEV_RELAY_PORT" \
TD_DAEMON="$TUTOR_DEV_DAEMON_PORT" TD_STATE="$TUTOR_DEV_STATE" TD_MOUNT="$TUTOR_DEV_MOUNT" \
TD_IMAGE="$TUTOR_DEV_IMAGE" TD_VERSION="$TUTOR_DEV_BB_VERSION" TD_URL="$TUTOR_DEV_URL" \
TD_POST_START="$TUTOR_DEV_POST_START" \
node -e '
const e = process.env;
const bb = {
  mode: "standalone",
  autoStart: true,
  serverPort: e.TD_PORT,
  hostDaemonPort: e.TD_DAEMON,
  dataDir: e.TD_STATE,
  appUrl: "auto",
};
if (e.TD_VERSION) bb.version = e.TD_VERSION;
const config = {
  name: `${e.TD_NAME} (tutor-dev BB plugin harness; generated by scripts/tutor-dev/up.sh)`,
  image: e.TD_IMAGE,
  features: { "./features/bb": bb },
  remoteUser: "node",
  workspaceMount: `source=${e.TD_MOUNT},target=${e.TD_MOUNT},type=bind`,
  workspaceFolder: e.TD_MOUNT,
  runArgs: ["--name", e.TD_NAME, "-p", `127.0.0.1:${e.TD_PORT}:${e.TD_RELAY}`],
  containerEnv: { BB_SERVER_URL: e.TD_URL, BB_DATA_DIR: e.TD_STATE, BB_HOST_DAEMON_PORT: e.TD_DAEMON },
};
// Runs after the bb Feature postStartCommand (bb-feature-autostart), which
// blocks until the BB server and host daemon are ready.
if (e.TD_POST_START) config.postStartCommand = e.TD_POST_START;
process.stdout.write(JSON.stringify(config, null, 2) + "\n");
' > "$dc_dir/devcontainer.json"

hash="$( { cat "$dc_dir/devcontainer.json"; (cd "$dc_dir/features/bb" && find . -type f | LC_ALL=C sort | xargs sha256sum); } | sha256sum | cut -d' ' -f1)"
hash_file="$TUTOR_DEV_HOME/applied-config.sha256"

existing="$(td_container_id)"
up_args=(up --workspace-folder "$TUTOR_DEV_WORKSPACE" --id-label "$TUTOR_DEV_LABEL")
if [ -n "$existing" ]; then
    if $rebuild; then
        td_log "--rebuild: recreating ${TUTOR_DEV_NAME}"
        up_args+=(--remove-existing-container)
    elif [ "$(cat "$hash_file" 2>/dev/null || true)" != "$hash" ]; then
        td_log "generated config or src/bb changed since last up; recreating ${TUTOR_DEV_NAME} (BB state is kept)"
        up_args+=(--remove-existing-container)
    fi
fi
if [ -z "$existing" ] || [[ " ${up_args[*]} " == *" --remove-existing-container "* ]]; then
    if [ -z "$existing" ] && ss -ltnH "sport = :${TUTOR_DEV_PORT}" 2>/dev/null | grep -q .; then
        td_die "host port ${TUTOR_DEV_PORT} is already in use; set TUTOR_DEV_PORT to a free port"
    fi
    $no_cache && up_args+=(--build-no-cache)
fi

td_log "devcontainer ${up_args[*]}"
"$DEVCONTAINER" "${up_args[@]}" > "$TUTOR_DEV_HOME/devcontainer-up.json" 2> "$TUTOR_DEV_HOME/devcontainer-up.log" || {
    tail -n 40 "$TUTOR_DEV_HOME/devcontainer-up.log" >&2
    td_die "devcontainer up failed; full log: $TUTOR_DEV_HOME/devcontainer-up.log"
}
grep -q '"outcome":"success"' "$TUTOR_DEV_HOME/devcontainer-up.json" || {
    cat "$TUTOR_DEV_HOME/devcontainer-up.json" >&2
    td_die "devcontainer up did not report success"
}
printf '%s\n' "$hash" > "$hash_file"
td_running || td_die "container ${TUTOR_DEV_NAME} is not running after devcontainer up"

# 2. Start the loopback relay (idempotent: it exits if its port is taken).
docker cp "$TUTOR_DEV_SCRIPTS/relay.mjs" "$TUTOR_DEV_NAME:/tmp/tutor-dev-relay.mjs" >/dev/null
docker exec -d -u "$TUTOR_DEV_USER" "$TUTOR_DEV_NAME" sh -c \
    "exec setsid node /tmp/tutor-dev-relay.mjs ${TUTOR_DEV_RELAY_PORT} ${TUTOR_DEV_PORT} >>/tmp/tutor-dev-relay.log 2>&1 </dev/null"

# 3. Confirm BB inside, then through the published port from the host.
td_exec bb-feature-status || td_die "bb-feature-status failed; see ${TUTOR_DEV_STATE}/.bb-feature/launcher.log"
for _ in $(seq 1 30); do
    curl -fsS --max-time 2 "${TUTOR_DEV_URL}/health" >/dev/null 2>&1 && break
    sleep 1
done
curl -fsS --max-time 2 "${TUTOR_DEV_URL}/health" >/dev/null 2>&1 \
    || td_die "BB is healthy inside the container but ${TUTOR_DEV_URL}/health is unreachable from the host (relay log: docker exec ${TUTOR_DEV_NAME} cat /tmp/tutor-dev-relay.log)"

td_log "ready: ${TUTOR_DEV_URL}  (container ${TUTOR_DEV_NAME}, bb $(td_exec bb --version 2>/dev/null | tr -d '\r'))"
printf '%s\n' "$TUTOR_DEV_URL"
